### ISSUE TITLE
Blank/empty extension menu (Firefox)

### ISSUE THREAD

**Issue by LBrinston** [duckduckgo/duckduckgo-privacy-extension#1626]
## Description
DDGPE extension becomes unresponsive in firefox:
1. Clicking DDGPE extension in the firefox toolbar opens "blank" drop down menu (it's just a blank menu - see Actual behaviour below for screenshot).
2. Clicking the DDGPE "generate private email" in right click menu does nothing (ie. no email is generated).
3. Trying to "sign-in" to DDG email does nothing.

Removing the extension, restarting firefox, and reinstalling the extension (with permission to function in private browsing mode) restores functionality however, once I restart firefox the extension is broken again. The makes the extension completely unusable as anytime I need to use it I am forced to close whatever it is I need a private email address for in-order to reinstall the extension.

## Steps to Reproduce
Honestly not sure what to put here as I don't know enough about web browsers to even speculate as to what might be causing the problem.
1. Install Firefox
2. Firefox settings: Check "Always use private browsing mode"
3. Firefox settings: Choose custom tracking protection (check cookies: cross-site and isolate, tracking content, crytpominers, and fingerprinting)
4. Install DDGPE extension and give it permission to operate in private browsing mode.

(I do have other extensions like ublock origin installed but disabling them hasn't made any difference)

**Expected behavior:**
Clicking DDGPE "generate private email" in right-click menu generates a private email.
Clicking DDGPE toolbar icon opens functioning menu:
![Screenshot 2023-01-02 143122](https://user-images.githubusercontent.com/66662229/210283138-a431b718-f32a-479d-b860-c569d42738d7.png)

**Actual behavior:**
Clicking DDGPE toolbar icon opens blank menu:
![Screenshot 2023-01-02 143209](https://user-images.githubusercontent.com/66662229/210283157-bd39bf7f-5c27-4297-b3f1-05c1018c5795.png)

**Versions**
- Extension: 2022.12.12
- Browser: Firefox 108.0.1 (64-bit)
- OS: Windows

## Additional Information
Provide additional context (optional):
1. This issue occurs every single time I restart firefox on two different machines (laptop/desktop both running windows)
2. Did this issue start after an upgrade to a new extension version? If so, can you repeat it using a previous extension version? Unclear however the extension did initially function for several months without issue.
3. Are there any errors in the extension debugging console? No idea how to even find this if it an option.

**Comment by sammacbeth** [comment]
Thank you for this report - I was able to reproduce the issue and find out what is causing it. I'm going to prepare a patch so we can hopefully have this fixed in the next release.

**Comment by LBrinston** [comment]
> Thank you for this report - I was able to reproduce the issue and find out what is causing it. I'm going to prepare a patch so we can hopefully have this fixed in the next release.
Amazing! Thank you : )

**Comment by sammacbeth** [comment]
This fix was now released. Can you check if the latest version is working for you? Thanks!

**Comment by LBrinston** [comment]
> This fix was now released. Can you check if the latest version is working for you? Thanks!

It appears to be working on both machines. Thank you!

**Comment by urielejh** [comment]
the issue is still present. latest version. edge 128.0.2739.9 (Official build) beta. worked until a few days ago
